### ISSUE TITLE
[Feature] setting to show count of unread messages, mentions or channels on taskbar

### ISSUE THREAD

**Issue by samogot** [mattermost/desktop#111]
When I receive message, there is small red badge with number of total unread messages appears on task bar. I would be great if user can chose what to count on this badge - any messages, mention and direct messages only or even number of channels with unread messages

**Comment by Shutterstrom** [comment]
I'm sort of looking for a notification setting like this... 

I'm looking for a notification more like the one in Slack but where there is the ability to show this red badge in (windows task bar icon) only for specified (or none) items.

I personally only want to have mentions as a notification in task bar icon, but if there is anything written in a channel I want the channel to be highlighted (in bold) so that I can see that someone have written something in the channel if I want to read it, even though I'm not mentioned in that post.

**Comment by Razzeee** [comment]
Mentions are red, and other texts give a green/blue ish dot now.

**Comment by Shutterstrom** [comment]
That's good, but if there was a setting for notifications on the task bar icon, what do react to and not, that would be good. 

But also some type of highlight on the channel (in left frame in Mattermost klient) that there have been things written in the channel... Now, if I want to see if there has been anything written in the channel I have to open the channel and look since I only what a notification in the taskbar for mentions. I'm looking for some type of highlight/notifications in the left frame of the specific channel where something have been written.

**Comment by jasonblais** [comment]
Thanks you @samogot for the suggestion!

It would be nice to get more feedback and discussion on this feature request. 

Could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed and upvoted? There are more forum visitors than GitHub issue visitors, which means a potentially faster response.

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
I've moved the suggestion to the [Feature Idea forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/15733626-add-a-configurable-setting-to-show-count-of-unread).

If you'd like to see the feature, you may upvote the feature request in the forum.

**Comment by webparadoxer** [comment]
any news about it?! I voted on idea forum
