### ISSUE TITLE
collapsable comments

### ISSUE THREAD

**Issue by kariesta** [mattermost/desktop#1236]
writing a large comment can overshadow other comments and sometimes you don't want to add it as a textfile, because it needs to be read.
It would be helpfull if we could collapse any text over, lets say, 10 lines to only show the first 2-3 lines when collapsed.

**Comment by Willyfrog** [comment]
hello! thanks for your suggestion, but that would happen also in the browser so it should be placed on our [server repo](https://github.com/mattermost/mattermost-server/issues/). Since I can't move issues from one repo to the other, can you please create the issue there? That way it will be taken into account by the right people :)

**Comment by kariesta** [comment]
Oh, right.
thanks for the redirection :)
