### ISSUE TITLE
Icon Badge and Highlight missing from Private Channels - Mac - 4.5.2

### ISSUE THREAD

**Issue by michaelswope** [mattermost/desktop#1355]
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Mac - 10.14.6
- Mattermost Desktop App version: X.X.X  4.5.2
- Mattermost Server version: X.X.X 5.15.0 Enterprise Edition

**Steps to reproduce**
Receive a message to any private channel
**Expected behavior**
Should have a red badge on the icon in the dock
**Observed behavior**
No badge present on icon in dock

**Possible fixes**

**Comment by Willyfrog** [comment]
does this only happen on private channels (no DM/GM/public)? does the post contain a mention? what are the settings for notifications on that channel?

**Comment by ahmaddanialmohd** [comment]
Hello, @michaelswope 

I will start by checking the settings of the app first by clicking on the following:

<img width="223" alt="Screenshot 2020-09-23 at 00 11 39" src="https://user-images.githubusercontent.com/49461314/93908616-70728680-fd31-11ea-9712-a91d0757c279.png">

You should then be able to see the following:

<img width="1071" alt="Screenshot 2020-09-23 at 00 10 58" src="https://user-images.githubusercontent.com/49461314/93908639-78cac180-fd31-11ea-9736-4f892cf9b538.png">

Ensure that the necessary checkboxes are ticked as well you are not in the **Do Not Disturb** status.

**Comment by teyeheimans** [comment]
We have the same issue. Small company with 8 users. Very annoying bug as you miss the messages.

**Comment by amyblais** [comment]
@teyeheimans Would you have more details on what you're seeing as requested by devs above? ^
 - https://github.com/mattermost/desktop/issues/1355#issuecomment-665511838
 - https://github.com/mattermost/desktop/issues/1355#issuecomment-696823976

**Comment by teyeheimans** [comment]
It seems to happen only in Direct Messages. Not in channels. The post did not contain a mention. 

We are unable to trigger it, because if I unfocus the window  (switch to another application), and my colleague talks to me, I do get a notification. However, I just had a case where a colleague needed to notify me over Skype because MatterMost did not notify me about his DM messages. This was after a period of 20+ minutes of inactivity. 

I hear this problem of more colleagues who have this issue. My general notification settings:

![Schermafbeelding 2021-06-08 om 16 28 26](https://user-images.githubusercontent.com/21109255/121203664-936ca880-c876-11eb-88ad-d4513a2bcb32.png)

The  DM channel is not muted. It seems only to happen after a longer time of inactivity.

**Comment by amyblais** [comment]
What Mattermost server version and OS are you on?
Are there any console log errors (instructions here https://docs.mattermost.com/install/desktop.html#reporting-issues)?

**Comment by teyeheimans** [comment]
I am on Mac OS 10.15.7.  We run mattermost server version 5.35.2-0 on Ubuntu 20.04. 

Here is my console log file. However, I have restarted in between. We will also make a log file after the first time it happens again. 

[-1623165215068.log](https://github.com/mattermost/desktop/files/6617720/-1623165215068.log)

**Comment by amyblais** [comment]
@Willyfrog FYI for above details.

**Comment by Willyfrog** [comment]
> The DM channel is not muted. It seems only to happen after a longer time of inactivity.

If you open the dev tools for the current server after leaving the app in the background and missing a notification, does it show any errors?

**Comment by Willyfrog** [comment]
regarding the errors on the log, the only error is about context menu not being able to generate a URL object out of whatever is being hovered, so nothing that would cause it.

Im asuming this is with the mattermost build, not a modified one, right?

**Comment by teyeheimans** [comment]
Correct, we just use the mattermost build. 

I have asked my colleagues to share the console log whenever the issue happens again. We also thought that it might be related to the server. We use nginx as proxy. We have used your example configuration as setup: https://docs.mattermost.com/install/config-proxy-nginx.html

Thanks for your help so far. We will provide mode input when it happens again.

**Comment by teyeheimans** [comment]
Ok, we had this problem again. See attached the requested log files.

Some things look interesting:

```
/api/v4/users/me/teams/unread:1 Failed to load resource: net::ERR_NETWORK_CHANGED

/api/v4/users/status/ids:1 Failed to load resource: net::ERR_TIMED_OUT

websocket_client.tsx:58 WebSocket connection to xxx failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

index_bundle.js:2744 Uncaught TypeError: Cannot read property 'current' of undefined
```

[application server.log](https://github.com/mattermost/desktop/files/6654830/application.server.log)
[current server.log](https://github.com/mattermost/desktop/files/6654831/current.server.log)

It is maybe related that the person who has had this issues is working on a VPN connection. However, he has not had any network related issues. He has not disabled the VPN connection.

**Comment by amyblais** [comment]
@Willyfrog For the log errors ^

**Comment by Willyfrog** [comment]
It looks like the websocket connection is having troubles to manage the network changes, if you don't have the websocket up it won't send the message to the client and the client won't show any notification/badges changes.

Does the user have to be connected to the VPN in order to connect to the mattermost server? if he doesn't maybe it is worth tring to use it without setting up the VPN.

If he absolutly needs to connect to the VPN I'd suggest switching to the browser and see if he gets the same problems.

I'd also suggest to review vpn and firewall rules and check that it is not blocking the websocket connection.

**Comment by devinbinnie** [comment]
@michaelswope @teyeheimans Does this still reproduce for you on v5.0.2?

**Comment by teyeheimans** [comment]
> @michaelswope @teyeheimans Does this still reproduce for you on v5.0.2?

I haven't had this issue anymore lately. I have also asked my team and there where no more complaints about this issue.

**Comment by Willyfrog** [comment]
Thanks! feel free to reopen if it starts happening again.
