### ISSUE TITLE
Own installation animation 

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#150]
It would be nice, to get someone to do a mattermost is now installing animation as a gif. So that we can use it when the setup runs.

**Comment by jasonblais** [comment]
FYI, there's some progress on this front, we should have a loading animation gif for 1.4!

**Comment by jasonblais** [comment]
In light of the progress from the Mattermost team, I have tentatively added this for the 1.4 milestone

**Comment by Razzeee** [comment]
Any news here @jasonblais ?

**Comment by jasonblais** [comment]
It didn't make it for Mattermost v3.3, but I'll push for it to be added for v3.4.

That will let us use it for the desktop app too.

**Comment by jasonblais** [comment]
Update: The GIF is *almost* ready now, @asaadmahmood will take a look at appropriate colouring for it as black might be too dark.

**Comment by jasonblais** [comment]
Unfortunately it didn't make it to Mattermost v3.4, so removing from v1.4 milestone.

**Comment by jasonblais** [comment]
The GIF loading icon is ready, attached is the 50x50 version below.

We should reduce opacity of the GIF by 0.5 so that the icon is grey rather than black - black is too heavy for the desktop app.

![2016-07-21 20_07_48](https://cloud.githubusercontent.com/assets/13119842/18682296/af053a5c-7f39-11e6-9dfc-d9c5a16a498d.gif)

**Comment by jasonblais** [comment]
We might want to build an installation wizard instead of using an installation icon. That's much more common for Windows
