### ISSUE TITLE
List unread messages on the top 

### ISSUE THREAD

**Issue by sjeeva** [mattermost/desktop#1505]
In a server with larger number of groups and user, it is difficult to find the unread messages.  It would be helpful to list the unread Public/Private/Direct message on the top of the nav bar.

Suggest features in the Mattermost feature idea forum so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html).

[https://mattermost.uservoice.com](https://mattermost.uservoice.com/forums/306457-general?category_id=159795)

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by Willyfrog** [comment]
hi there, and thanks for the feedback. 
If I'm not mistaken that feature already exists, since several versions. With the new sidebar it looks like this
<img width="230" alt="Screenshot 2021-03-11 at 10 56 24" src="https://user-images.githubusercontent.com/1515906/110769521-8b41a480-8258-11eb-98bd-e4332bd74de9.png">

I'm closing the issue, but please reopen if you feel I missunderstood your request
