### ISSUE TITLE
Notification design improvements for OS X

### ISSUE THREAD

**Issue by kethinov** [mattermost/desktop#151]
The current design of the native electron-driven OS X notification could use some design improvements.

Here is Slack's:

![screen shot 2016-05-25 at 3 21 20 pm](https://cloud.githubusercontent.com/assets/419567/15553425/fb0dc6b2-228c-11e6-90ad-4b6aca8aaca4.png)

And Mattermost's:

![screen shot 2016-05-25 at 3 19 17 pm](https://cloud.githubusercontent.com/assets/419567/15553437/05c84abe-228d-11e6-826e-993f4c1642ec.png)

Some things that might be worth doing:
- One Mattermost icon instead of two.
- Align the notification text to the top. (Or at least add two lines.)
- Consider formatting the notification to use bold for message boilerplate and non-bold for content (similar to Slack).

**Comment by yuya-oc** [comment]
- [x] icon
- [ ] text alignment
- [ ] format

**Comment by Razzeee** [comment]
I think we should try to shim and notify for the longrun.
See: https://github.com/Razzeee/desktop/commit/397b53f51d2298eebdc60000140e26bd07bbe865#diff-59f51de4945d3a9a80a254062862997bR17 which is wip but it should work, but I haven't been able to test it, as I don't have access to an mattermost instance, where I can create test accounts and just write myself to generate notifications :/

**Comment by yuya-oc** [comment]
It seems that the commit doesn't work as I think. In my memory, Electron's `Notification.onclick` doesn't change window's focus state, so we should handle `onlick` manually in this kind of app. Then, `onNotificationClick` event should be sent on `onclick` in order to switch to the notified tab.

BTW, you can use a local machine like VirtualBox or Docker to host mattermost server for testing.

**Comment by yuya-oc** [comment]
@kethinov I think the notification should show both of channel name and message. Could you check again?

Off Topic channel:
![notification](https://cloud.githubusercontent.com/assets/1412057/15895478/86ece39a-2dc6-11e6-943f-fa9c5b69c860.png)

Mattermost server: 3.0.3
Mattermost desktop: 1.2.1
OS X: 10.11.3

**Comment by Razzeee** [comment]
After looking into it, I don't think we should do ```Consider formatting the notification to use bold for message boilerplate and non-bold for content (similar to Slack).```
as this is probably something the guys from the platform would need to change centrally.
https://github.com/mattermost/platform/blob/c0d1b8fbb9a141b942d73ad4869e612cdf01bbcd/webapp/stores/notification_store.jsx#L86
We could only do it very very hacky and it will be likely to break with new translations etc.

@it33 fyi

**Comment by jasonblais** [comment]
The OS X notification appears reasonable to me at its current state - however, it is missing the Mattermost logo, and I will file a separate ticket for it.

Given
 - One Mattermost icon is used instead of two
 - Notification text is aligned to the top with channel name with channel name bolded on the first line and message content unbolded below it

we're ready to close this issue. Below is a screenshot of OS X icon for reference.

![image](https://cloud.githubusercontent.com/assets/13119842/17045111/d20f283e-4f94-11e6-80a9-ad556d24f671.png)

**Comment by Razzeee** [comment]
@jasonblais 
Was there a change in the platform that changed the title ("Direct Message")? DMs previously had non set. So that was what caused the Notifications to look so ugly, like the author of this mentioned. Or like in my screenshot.

![notification](https://cloud.githubusercontent.com/assets/5943908/17050620/39061f16-4ff4-11e6-9dcf-6fdaf2055dd4.png)

**Comment by jasonblais** [comment]
@Razzeee 

There was indeed a change made [to v3.2 by the platform team](https://mattermost.atlassian.net/browse/PLT-3328), which now shows the "Direct Message" title for DMs.

**Comment by Razzeee** [comment]
Perfect! Thank you.
