### ISSUE TITLE
Auto reconnect to Mattermost server after the VPN Connection established. 

### ISSUE THREAD

**Issue by ndgayan** [mattermost/desktop#2002]
I set up the Mattermost client desktop application to start with windows and connect to our Mattermost server. Our Mattermost server can access through the VPN, and I need to manually log in to the VPN server after restarting my PC. Mattermost client desktop applications never retry to connect to the server after establishing the VPN connection (I set the Client app to start with Windows). I need to manually close the Mattermost client application from the taskbar tray and restart it after connecting to the corporate VPN network. I forgot to do this step (most of the time); after restarting my PC, I'm missing all the notifications. Could you add an auto-connect option to the list of servers if the client is not connected during the autostart of the client app (in Windows)?

**Comment by devinbinnie** [comment]
Thanks for the suggestion @ndgayan! I like this idea, seems like a good QoL improvement. I'll have to investigate to make sure it's possible and we'll see if we can implement it at some point in the future.

**Comment by ndgayan** [comment]
Thank you for the quick reply. I appreciate It, and kudos to you guys and this fantastic project.

**Comment by bbodenmiller** [comment]
By the way this used to happen before the 5.0 desktop update so I think this is actually a bug.

**Comment by devinbinnie** [comment]
Created a ticket here: https://mattermost.atlassian.net/browse/MM-42065

**Comment by equada** [comment]
Also experiencing the same, the client offers no nice way to reconnect. No F5, no rightclick, no button, 
I have to close it via system tray as ndgayan already described.
If an automatic re-connect is too much work, maybe just add a refresh button to the error page as a first step

**Comment by mrhmrhmr** [comment]
Good morning!

I am also waiting since a couple of months to get this one solved.
**First connection attempt** to the server **fails**, the Desktop Client does not try to reconnect automatically.
As this potentially **affects all people working from home** and **having the need to connect via VPN manually** I would be interested to get some higher priority on it :).

If I well remember it was working before version 4.6.x.
As suggested by @equada it would be "ok" from a users perspective to have a simple button to reconnect manually as a first fast fix before implementing some kind of automatic polling if not connected to a server (Maybe it´s just a check if a Websocket is established or not).

**Comment by equada** [comment]
Thank you very much for fixing, meanwhile I found out that Ctrl+R works for reloading ^^
