### ISSUE TITLE
Assets missing on GitHub Release post

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/desktop#2113]
https://github.com/mattermost/desktop/releases/tag/v5.1.0 is missing release assets whereas https://github.com/mattermost/desktop/releases/tag/v5.0.4 had them. This is required because this is the only approved download source for some users for the desktop client.

**Comment by bbodenmiller** [comment]
Might be related to https://github.com/mattermost/desktop/pull/1810 or https://github.com/mattermost/desktop/pull/2059

@elyscape @Willyfrog @devinbinnie

**Comment by devinbinnie** [comment]
@bbodenmiller Can you provide reasoning why users are not able to download from our website? I would like to understand the requirements better. Thanks!

**Comment by elyscape** [comment]
This happens because `ghr`, the tool used to [create the GitHub release][upload], only looks at [the immediate descendents of provided paths][ghr]. The contents of `ghr-dist/` are assembled with this in mind.

The various build jobs place the release assets into the build workspace under the paths [`linux/`][linux], [`macos-release/`][macos-release], and [`win-release/`][win-release]. In the release job, the build workspace is attached to `build/`, after which `build/{macos-release,win-release,linux}/*` [is copied into `ghr-dist/`][copy].

The problem is that, as part of #1714, the build jobs were modified to place the release assets into versioned subdirectories of `macos-release/`, `win-release/`, and `linux/`. As a result, when `ghr` begins execution, the contents of `ghr-dist/` look something like this:
```
ghr-dist/
├── 5.1.0
│   ├── mattermost-desktop-5.1.0-linux-i386.AppImage
│   ├── mattermost-desktop-5.1.0-linux-i686.rpm
│   ├── mattermost-desktop-5.1.0-linux-ia32.tar.gz
│   ├── mattermost-desktop-5.1.0-linux-x64.tar.gz
│   ├── mattermost-desktop-5.1.0-linux-x86_64.AppImage
│   ├── mattermost-desktop-5.1.0-linux-x86_64.rpm
│   ├── mattermost-desktop-5.1.0-mac-m1.dmg
│   ├── mattermost-desktop-5.1.0-mac-universal.dmg
│   ├── mattermost-desktop-5.1.0-mac-x64.dmg
│   ├── mattermost-desktop-5.1.0-x64.msi
│   ├── mattermost-desktop-5.1.0-x86.msi
│   ├── mattermost-desktop-setup-5.1.0-win.exe
│   ├── mattermost-desktop_5.1.0-1_amd64.deb
│   └── mattermost-desktop_5.1.0-1_i386.deb
├── builder-debug.yml
├── builder-debug.yml.~1~
├── builder-debug.yml.~2~
├── latest-linux-ia32.yml
├── latest-linux.yml
├── latest-mac.yml
└── latest.yml
```
Since `ghr` doesn't recurse, it only picks up the `yml` files at the root, resulting in no useful release assets being uploaded to GitHub.

One way to fix this would be to just include the version in the `cp` command:
```shell
mkdir -p ./ghr-dist
VERSION=$(jq -r .version package.json)
cp -r --backup=numbered ./build/{macos-release,win-release,linux}/${VERSION}/* ./ghr-dist
```
An alternate, somewhat more resilient fix would be to use `find` to enumerate and copy the various build subdirectories.
```shell
mkdir -p ./ghr-dist
find ./build/{macos-release,win-release,linux} -type f -exec cp --backup=numbered -t ./ghr-dist {} +
```
This has the benefit of not needing updates if further changes are made down the line within the build subdirectories, and could even be simplified further if the Linux build job were updated to place its output into `build/linux-release`:
```shell
mkdir -p ./ghr-dist
find ./build/*-release -type f -exec cp --backup=numbered -t ./ghr-dist {} +
```
As an aside, I would recommend either renaming the `build-debug.yml` files to include the platform name, such that they won't collide, or not including them as release artifacts. This would allow for the `--backup=numbered` flag to be removed.

[copy]: https://github.com/mattermost/desktop/blob/v5.1.0/.circleci/config.yml#L493-L497
[ghr]: https://github.com/tcnksm/ghr/blob/v0.14.0/local.go#L31
[linux]: https://github.com/mattermost/desktop/blob/v5.1.0/.circleci/config.yml#L163-L166
[macos-release]: https://github.com/mattermost/desktop/blob/v5.1.0/.circleci/config.yml#L343-L349
[upload]: https://github.com/mattermost/desktop/blob/v5.1.0/.circleci/config.yml#L481-L513
[win-release]: https://github.com/mattermost/desktop/blob/v5.1.0/.circleci/config.yml#L238-L242

**Comment by elyscape** [comment]
Update: adding the version to the `cp` command will break the upload of the assorted `latest.yml` files, as those don't get placed in the versioned subdirectories.

**Comment by bbodenmiller** [comment]
> @bbodenmiller Can you provide reasoning why users are not able to download from our website? I would like to understand the requirements better. Thanks!

@devinbinnie various organizations only allow downloads via approved proxies (e.g. via Artifactory). GitHub is easy to configure as a remote repo in Artifactory whereas https://releases.mattermost.com appears impossible to setup as Artifactory remote repo.
