### ISSUE TITLE
MSI Installer not compatible with Updater

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/desktop#2175]
**Summary**
MSI Installer doesn't work with integrated updater

**Steps to reproduce**

- Install MSI Installer 5.1.0
- Start Mattermost
- Mattermost offers to update
- let it update
- Mattermost download and installs the exe installer which installs in %appdata%
- You have two installations

**Expected behavior**

The MSI Installer should be downloaded and installed

**Observed behavior**

The exe installer is downloaded and installed.

**Comment by devinbinnie** [comment]
Ahh yes, I didn't think about this one. Unfortunately I don't believe we have a choice as to what installer it downloads. The auto-updater provided by `electron-updater` makes that choice for you.

I think the best course of action here would be to disable auto-updates for the MSI installer, since its existence is more for system administrators to be able to control the versioning themselves as well as distribute to a larger number of systems, which gets fuzzy if we allow users to auto-update with it.

**Comment by devinbinnie** [comment]
Created a ticket here: https://mattermost.atlassian.net/browse/MM-45409
