### ISSUE TITLE
Refreshing takes me to the team selection page

### ISSUE THREAD

**Issue by lfbrock** [mattermost/desktop#223]
#### Summary

Refreshing the page takes me back to the team selection page.

#### Steps to reproduce

On Mac desktop app, v1.3: 
1. Log into a team
2. Open any channel
3. Refresh the page

#### Expected behavior

I should stay on the current channel, and the page should refresh.

#### Observed behavior

I am taken back to the team selection page.

**Comment by yuya-oc** [comment]
Would you check the URL which you inputted in the settings page? The settings page expects that the URL includes team (e.g. https://example.com/team). And please write about server version.

**Comment by Razzeee** [comment]
Might be a nice improvement, if we can grab the team and save it for the user?

**Comment by jasonblais** [comment]
@yuya-oc @Razzeee I just reproduced the case and it refreshes to whatever URL you specified on the settings page. So whether it's `https://example.com`, or  `https://example.com/team`, etc.

It would be nice if the user remained in the team + channel they were viewing before refreshing the page. That is,

 1. User is on [team 2] (second team in the tablist), in [channel 1]
 2. Refreshes the page

#### Observed behavior: 
User taken to the URL of **[team 1]** I specified in the settings page (so different team, and a different channel after refresh)

#### Expected behavior: 
I stay in [channel 1] of [team 2] after refresh.

**Comment by yuya-oc** [comment]
Now "Reload"(Ctrl+R) refresh all of UI including tabs in the main page. So webview tries reloading the URL which is specified in the settings page. So "Reload" should refresh the activated tab only.

**Comment by yuya-oc** [comment]
Closed by dcbf18e
