### ISSUE TITLE
Settings UX

### ISSUE THREAD

**Issue by edlerd** [mattermost/desktop#2266]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
There are two settings menus. 
As a user, it is confusing. I didn't expect a second menu after discovering the first one.

**Environment**
- Operating System: Linux
- Mattermost Desktop App version: 5.1.1
- Mattermost Server version: 6.6.0

**Steps to reproduce**

- First menu: click "three dots top left" > file > settings for electron / app stuff.
- Second menu: click "gear icon on top right" which also exists in the web browser version

**Expected behavior**
There should be just one menu.

**Observed behavior**
There are two menus.

**Possible fixes**
Merge the menu items.

**Comment by devinbinnie** [comment]
This exists because the two Settings menus are not part of the same application as it were. The Desktop App has its own Settings window for the Electron stuff, and then the Settings in the Web App are part of the React app that we run in a BrowserView.

We will be looking into merging these in the future if possible but under the architecture this is not currently possible.
Closing for now.
