### ISSUE TITLE
CTRL/CMD+F on Desktop app puts cursor in Mattermost search box filtered to channel

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#229]
Propose in the Desktop app, CTRL/CMD+F brings up
 a) Mattermost search 
 b) all search results **pre-filtered to the channel** (i.e. search text is `in:[channel_handle]`)

This would have a similar effect to the browser CTRL/CMD+F and would be a nice improvement to user experience.

**Comment by jasonblais** [comment]
We have received feature requests from several sources, would be great if we got this in for v1.4

Original uservoice request: https://mattermost.uservoice.com/forums/306457-general/suggestions/15020541-ctrl-f-on-windows-desktop-app-puts-cursor-in-matte

**Comment by Razzeee** [comment]
I had a look, but doing keybindings in electron kinda sucks. As they are system global. So the only way to have them for when the program is focused, is to set them up and tear them down each time the app gets focus or looses it. Which wasn't very reliable when I tested it. 
See https://www.npmjs.com/package/electron-shortcut for e.g.

**Comment by jasonblais** [comment]
Thanks for looking into it @Razzeee! 

Would there be an alternative to CTRL/CMD+F? I'm surprised electron wouldn't have added better support for it given it's a common functionality.

**Comment by Razzeee** [comment]
I still fear the problem of this not working is somehow app specific, as we also have problems with the notification stuff and electron-context-menu which all have problems out of the box.
Maybe also react specific? 
@jnugh

**Comment by jnugh** [comment]
Instead of binding the keys using electron it should be possible to listen to keydown in react, I guess.
However how did you bind the event?
When you use document as a target it should not be global as in system wide!

**Comment by Razzeee** [comment]
Well I just used auto bind as in the examples here. https://github.com/ragingwind/electron-shortcut#usage
Which works for the first time, but then just stops working.

**Comment by jnugh** [comment]
You can try to open the developer tools and add a breakpoint to the focus event.
See if it gets caught by react.

**Comment by yuya-oc** [comment]
I'm not sure why you are considering global-shortcut, how about implementing the Ctrl+F shortcut at `src/main/menus/app.js`? Then open the search-box described by @jasonblais. We can inject js code by `src/browser/webview/mattermost.js`, so maybe we can trigger the function via `ipcRenderer`.

FYI, Electron provides [APIs to implement find-in-page features like web browsers](http://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options). But it seems a little hard because it doesn't provide any UI.

**Comment by Razzeee** [comment]
Well I don't think this should have a menu entry. It might be a plan b but it feels weird to me.

**Comment by yuya-oc** [comment]
`MenuItem` has `visible` property, but I think it's not bad idea to indicate the shortcut by using its menu entry.

FYI, Slack's CMD+F performs like the case b. It opens the search pane in the right side of the window and enters `in:[current_channel]` filter.

**Comment by jasonblais** [comment]
Prepared a note last night but never hit 'Comment'..

I checked other Windows apps and including `Find` under **Menu Bar > Edit** seems to be relatively common.

Ideally I think a global shortcut would be nice, but I don't see adding it to the menu bar would be terrible. Thoughts @Razzeee?

**Comment by Razzeee** [comment]
I tried that yesterday, got stuck on setting the focus to the box. As getElementsByClass name didn't work. Maybe due to the hierarchy of windows. In fact it would be nice, if those input elements got ids.

**Comment by jasonblais** [comment]
Thanks @Razzeee for trying it out! This would be a great improvement for the app.

Would anyone from the community have additional thoughts? @jnugh @yuya-oc ?

**Comment by jnugh** [comment]
@Razzeee: Where did you register the listener? This would need to be handled inside the webview to work. If you are outside you cannot access the search box.

**Comment by yuya-oc** [comment]
You can inject the code into webview via `src/browser/webview/mattermost.js`. Just experimentally implemented at 647e396. This can focus to the search box. However, it seems `<input>.value = STRING` does not properly work because probably the value is controlled by the state of React.js component. So we somehow have to pre-enter the keyword.

**Comment by yuya-oc** [comment]
Just tried filling `in:[channel_handle]` at 7e3acf6. Any thoughts about this artifact?

https://circleci.com/gh/mattermost/desktop/560#artifacts

**Comment by Razzeee** [comment]
Almost, the focus doesn't seem to be set correctly on the first time pressing the shortcut. After that it's working.
Another thing I would have done different, if there already is something in the search field, CTRL+F will only switch focus to the input. I would have emptied the input field, filing ```in:[channel_handle]````and then setting the focus.

**Comment by jasonblais** [comment]
@yuya-oc Great work here! Love it! :) 

I seem to get focus on the first try, does this reproduce for you each time @Razzeee? Do keyboard shortcuts work for you on first time pressing the shortcut (say `CTRL+K`)?

@Razzeee Interested to hear your thoughts behind clearing the search filed each time `CTRL+F` is pressed? On the browser, `CTRL+F` either 
1. opens search with focus, or 
2. sets focus back to the search bar with the current search term highlighted

The second gives the user an opportunity to decide whether they want to 
a) start a new search (as the search term is highlighted and typing a letter clears the field) or 
b) modify the search term by pressing the left or right arrow keys

**Comment by Razzeee** [comment]
Yes, it's happening every time for me. Even happens after switching team tabs. ```CTRL+K``` seems to have similar but other problems, that one just doesn't trigger due to focus. ```CTRL+F``` triggers but the carret isn't showing up.

![2016-08-19_11-17-04](https://cloud.githubusercontent.com/assets/5943908/17805194/87954cd6-65fe-11e6-9ad6-6bcb110fb153.gif)


In my mind it's different on our usecase, as we have the channel injected.
1. So if I go to a channel/dm
2. CTRL+F search something + Hit enter
3. Switch to another channel/dm
4. Hit CTRL+F 

Behaviour:
You still have the other channel selected and also the same search. When your in a whole different context/channel.

Expected:
I wanted to search this channel, not the other one I might already have forgotten about.

**Comment by yuya-oc** [comment]
About focus issue and Ctrl+K, I think probably they are similar or same. It seems the problem is that `<webview>` doesn't have focus properly.
- Focus: When clicking a tab, the focus is owned by the tab.
- Ctrl+K: When returning to the window, the webview's focus is stolen by the parent html.

**Comment by yuya-oc** [comment]
About the usecase, I could not decided which is better.

Just researched Slack now. `in:[channel_handle]` is updated to current channel when pressing Ctrl+F. If the box doesn't have channel_handle, `in:[channel_handle]` is inserted at the leading of existing words.

**Comment by jasonblais** [comment]
There definitely are some related focus issues (such as [reported here](https://github.com/mattermost/desktop/issues/231)). I got it reproducing with `CTRL+F` as well now so I think it's the same issue.

As for the use case: @Razzeee, that makes sense, which is `CTRL+F`
 - empties the input field
 - fills `in:[channel_handle]`
 - sets focus to the search bar

each time the shortcut is used.

**Comment by yuya-oc** [comment]
Updated and prepare the PR #258.
