### ISSUE TITLE
move dependencies bundled by webpack to devDependencies

### ISSUE THREAD

**Issue by selfisekai** [mattermost/desktop#2342]
every js dependency (excluding the 2 listed here, which include native code and should not be a subject to this: https://github.com/mattermost/desktop/blob/master/webpack.config.main.js#L28-L29) is bundled by webpack into the files in dist/ directory.

moving them to devDependencies breaks nothing and reduces package builds from ~80 MiB to ~20 MiB (excluding electron builds in both).

I was about to submit a PR myself, but the data requested in contributor agreement is insane.

**Comment by selfisekai** [comment]
the webpack output is the same, but the dependencies (excluding devDependencies) from node_modules/ are packaged by electron-builder into app.asar

**Comment by devinbinnie** [comment]
@selfisekai @tboulis Did some playing around and turns out this would help reduce the package size a bit. On Windows, looks like about 10-15 MB. I am noticing that the app.asar file is also smaller.

I think what's happening by doing this is making it so that we don't drop a bunch of source code for node_modules in the package, which is what was happening before.

I'll make a PR with the changes and tag this issue. Thanks for the suggestion :)
