### ISSUE TITLE
Merge resource folders

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#297]
I may be confused right now, but maybe we can merge the two resource folders
https://github.com/mattermost/desktop/tree/master/src/resources
https://github.com/mattermost/desktop/tree/master/resources

And remove one of them, as it is a little confusing to have two of these.

**Comment by yuya-oc** [comment]
Originally they have different purpose because I want to know explicitly which resources are used.

- `src/resources`: Resources which are loaded from the app codes.
- `resources`: Resources which are used outside of the app codes, e.g. application icons, installer icons, original SVGs of `src/resources`.

So possibly does renaming `src/resources -> src/assets` make sense?

**Comment by Razzeee** [comment]
Well if you ask me let's just add a `readme.md` to each folder and explain that. That would work for me :)

**Comment by yuya-oc** [comment]
Added `docs/development.md`.
