### ISSUE TITLE
Tray icon on Linux is too large

### ISSUE THREAD

**Issue by Brottweiler** [mattermost/desktop#317]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

The tray icon on Linux is just not looking that great, but the biggest issue I think is that it is too large compared to my other icons.
#### Steps to reproduce
1. Run Mattermost 3.4.0 on Linux.
2. Enable "icon in menu bar".
3. Make sure to have a tray available to see the "menu bar icon".
- Operating System: Arch Linux
- Mattermost Desktop App version: 3.4.0
- Mattermost Server version: 3.4.0
#### Expected behavior

To see a tray icon that matches other tray icons in size.
#### Observed behavior

![](https://i.imgur.com/EMGXdnO.png)

Icons are, from left to right: CopyQ, DeaDBeeF, Discord, Mattermost, volume, Slack, Steam, Telegram.

Notice how the Mattermost tray icon is larger than other icons, and does not fit. It's pretty ugly.
#### Possible fixes

I believe you may just need to add some padding around the logo. The edge of the logo itself probably touches the edge of the entire image, while for other icons there some padding? I am not entirely sure.

While we're at it, the "unread counter" is a black blob with red border, this _could_ be done nicer, imo. That dot is also rather large. Maybe take inspiration from how the Slack icon handles unread messages?

**Comment by St-Ex** [comment]
Hello,
On Mint 18 with cinnamon it's ok.
![trailer-mattermost](https://cloud.githubusercontent.com/assets/2870576/18904447/5ae9ffae-855e-11e6-85fc-980b8dc64184.png)

Would you have an option to choose between 2 size of icon ?

**Comment by Brottweiler** [comment]
I should have mentioned I am using XFCE, and the [mattermost-desktop](https://aur.archlinux.org/packages/mattermost-desktop/) AUR package. 

Option? Where?

**Comment by St-Ex** [comment]
Currently there is no option to do so. I was thinking of one, perhaps add a scale factor on the icon.

**Comment by Brottweiler** [comment]
@St-Ex I don't think no other application has a "scale factor" for the icon. There's something about the icon that just makes it look off...

Do you mean the same image size? Maybe the actual logo inside the image is different size, though? I guess it might just look like it's larger. I definitely think the icon is out of place, maybe replacing it with a different icon would be good.

**Comment by yuya-oc** [comment]
In my understanding, need padding around the logo in the png (the read square).

<img alt="menuiconmentiontemplate" src="https://cloud.githubusercontent.com/assets/1412057/18918465/e2330e16-85d5-11e6-876a-9057442c475d.png">

It would make better, but what size is consistent in Linux desktop? Are there any guidelines?

**Comment by jneureuther** [comment]
In kde (plasmashell 5.8.1) it is also totally broken: ![wtf1](https://cloud.githubusercontent.com/assets/4653434/20544989/f250f71a-b10c-11e6-99ae-e656eb0e2757.png)

**Comment by frittentheke** [comment]
Just like @nightvisi0n said ... on Mint 18 KDE (Plasma) it's broken and almost invisible using a dark threme.

**Comment by dejadejoder** [comment]
Hi,
tray icon is invisible on i3wm (http://i3wm.org/).

**Comment by dejadejoder** [comment]
Icon appeared this morning.
I didn't restart the OS but I restarted Mattermost.
![screenshot_20170310_103500](https://cloud.githubusercontent.com/assets/2197555/23797201/62e9e8f0-057d-11e7-91f4-61df5822bced.png)

**Comment by wget** [comment]
Hello everyone.

I was complaining of this issue as well. I tried several tricks.

* Adding a padding to the icon image not working. The image still takes the same width end height.
* If the icon is not visible on KDE Plasma, this is maybe due to the fact by default light is choosen. You can change the application references (`File` -> `Settings...` in the desktop app):
![screenshot_20180705_141309](https://user-images.githubusercontent.com/2997662/42322651-98b221da-805d-11e8-9152-a16e831db240.png)
 Please pay attention that the `dark` and `light` values here are not related to your desktop theme. You must choose them in reverse order. For dark theme desktops, choose `light`. For light desktops, choose `dark`.
* The position issue is due to the [GTK tray implementation of electron](https://github.com/electron/electron/blob/master/atom/browser/ui/tray_icon_gtk.cc).
* This issue could ultimately be fixed by [implementing SVG support](https://github.com/electron/electron/issues/9642) and overhauling the GTK tray support directly on electron.
* The `electron` text appearing as overlay when hovering the tray is not due to Mattermost but also to the electron GTK implementation (happening with Riot - electron based app - as well).
![screenshot_20180705_140424](https://user-images.githubusercontent.com/2997662/42322785-0a3fccbc-805e-11e8-9b6f-74fd32284961.png)

**Comment by wget** [comment]
https://github.com/meetfranz/franz/issues/233

**Comment by wget** [comment]
I have made further tests wrt GTK Status Icon.
Here is the code I used on different desktop environments:
```
#include <gtk/gtk.h>
#include <stdlib.h>
 
void quitMenu(GtkWidget *p_widget, gpointer user_data) {
    printf("Mattermost is quitting\n");
    gtk_main_quit();
}
 
void sysTrayMenu(GtkStatusIcon *status_icon, guint button, guint activate_time, gpointer user_data) {
    GtkWidget *menu = gtk_menu_new();
    GtkWidget *item = gtk_menu_item_new_with_mnemonic("Quit Mattermost");
	gtk_menu_shell_append(GTK_MENU_SHELL (menu), item);
	g_signal_connect_swapped(item, "activate", G_CALLBACK(quitMenu), NULL);
	gtk_widget_show_all(menu);
	gtk_menu_popup(GTK_MENU(menu), NULL, NULL, gtk_status_icon_position_menu, status_icon,button, activate_time);
}
 
int main (int argc, char ** argv) {
    GtkWidget *pWindow = NULL;
    GtkStatusIcon *pSysTrayIcon = NULL;

    gtk_init(&argc, &argv);
    pWindow = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_position(GTK_WINDOW(pWindow), GTK_WIN_POS_CENTER_ALWAYS);
    gtk_window_set_title(GTK_WINDOW(pWindow), "Mattermost systray test");
    g_signal_connect(G_OBJECT(pWindow), "destroy", G_CALLBACK(gtk_main_quit), NULL);

    // Status icon
    pSysTrayIcon = gtk_status_icon_new_from_file("./mattermost.png");
    gtk_status_icon_set_tooltip_text(pSysTrayIcon, "The text as tooltip");
    printf("DEBUG tooltip text: %s\n", gtk_status_icon_get_tooltip_text(pSysTrayIcon));
    fflush(stdout);

    g_signal_connect(G_OBJECT(pSysTrayIcon), "popup-menu", G_CALLBACK(sysTrayMenu), pWindow);
    gtk_widget_show_all(pWindow);
    gtk_main();
    return 0;
}
```
I made the tests using GTK2 and GTK3 to show case the differences between both library versions.
If you're using Fedora, install `gtk2-devel` and `gtk3-devel` in order to have all the requirements for pkg-config.

Compilation lines:
* For GTK2:
   ```
   gcc -Wall  notif.c $(pkg-config --libs --cflags  gtk+-2.0) -o notif
   ```
* For GTK3:
   ```
   gcc -Wall  notif.c $(pkg-config --libs --cflags  gtk+-2.0) -o notif
   ```
# Results

On Gnome, the status icon is not really useful. Tooltips and icons are not displayed. Only the actions implemented on the right click are actually used:
![gtk_status_icon_fedora_gnome](https://user-images.githubusercontent.com/2997662/42411689-541a6f4c-8200-11e8-8db3-5c2cf17806f7.png)

On LXQT, depending on the GTK version, the result is different, but the status, tooltips and right click actions are working like expected.
GTK2:
![gtk_status_icon_fedora_lxqt_gtk_2](https://user-images.githubusercontent.com/2997662/42411694-68ea478a-8200-11e8-86f2-0b3555c05dd1.png)
GTK3:
![gtk_status_icon_fedora_lxqt_gtk_3](https://user-images.githubusercontent.com/2997662/42411697-6ed5ef0a-8200-11e8-8d41-42af694c892d.png)

On KDE Plasma 5, the right click action and icon are working like expected, the tooltip is not taken into account. Only the name of the executable is important here. On Linux, this means that using a shell (like the following line) to launch Mattermost desktop is not a good solution:
```
electron /usr/lib/mattermost-desktop/app.asar --disable-dev-mode "$@"
```
Because such a configuration will display `electron` as application name in the tray location on Plasma 5. Maybe using a JS wrapper could help. [See here for more info how to do this](https://git.archlinux.org/svntogit/community.git/tree/trunk/atom.js?h=packages/atom). This is a point I still need to test.
![gtk_status_icon_arch_linux_plasma_5](https://user-images.githubusercontent.com/2997662/42411719-de4b9998-8200-11e8-90f4-4503252dbf42.png)

If we want to support SVG icon, hacking the status icon code in Google Chromium is needed because the Tray implementation of electron is based on the Chromium implementation. See [this file](https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/ui/libgtkui/gtk_status_icon.cc) on their repo.

**Comment by ArchangeGabriel** [comment]
There seems to be a workaround though: https://forum.kde.org/viewtopic.php?f=289&t=139804&sid=126b7c810ffe90ca3247790b364770ea&p=400696#p400696

**Comment by ArchangeGabriel** [comment]
Some great news from here: https://github.com/vector-im/riot-web/issues/6767#issuecomment-412674274

Chromium code has been fixed in libappindicator case while GTK StatusIcon is being deprecated. Chromium 70 should contain the fix, and when Electron will use this version it should be fixed too.

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14131

**Comment by pedroSBastos** [comment]
Hello,
On Manjaro 18.02 XFCE  looks bad:

![screenshot_2019-02-14_11-20-45](https://user-images.githubusercontent.com/34692188/52783746-bdb54f00-304a-11e9-8496-5512925d4574.png)

I am using mattermost-desktop from AUR package.

**Comment by emergie** [comment]
another nuance: mm icon looks ugly on the side panel in gnome 3
![mm](https://user-images.githubusercontent.com/2456881/53420108-71b7c200-39db-11e9-968a-de50c96e0831.png)

**Comment by skewty** [comment]
over 3 years and nothing has been done.  Linux and it typical minimized importance due to market share..  Does anyone have a link to any relevant Electron upstream issue(s)?

**Comment by ArchangeGabriel** [comment]
Electron 8.x completely changed the way tray icon are handled. I have not tried Mattermost Desktop with this electron version because I am currently not part of any Mattermost instance, but I guess it’s worth the try.

**Comment by tomasnorre** [comment]
I don't know if this is of importance to you. But I've experienced this with Slack and rambox too, so don't know if it's general Ubuntubudgie problem in my case or if it's all apps having the same issue.

Sounds more like the first one.

**Comment by elsiehupp** [comment]
I came to this issue from [one on the Electron GitHub](https://github.com/electron/electron/issues/9642), and in my limited experience with Ubuntu AppIndicator icons, basing the margins on the ones used by [GNOME's "symbolic" icons](https://developer.gnome.org/hig/stable/icon-design.html.en) seems to work reasonably well. Specifically, these are based on a 16x16 grid (though the dimensions of the actual PNG export can be a larger base-2 multiple for better downscaling to Electron's fixed tray-icon dimensions), and the artwork should fit within 14x14 units on the 16x16-unit canvas. If Chromium is updated to support SVG tray icons, they would probably also be tinted according to the desktop theme, since that's how GNOME (and presumably also KDE) treats SVG "symbolic" icons.

**Comment by enginhu** [comment]
Using Arch Linux with Gnome 40 and have the same issue. ![2021-04-29_11-14](https://user-images.githubusercontent.com/10974453/116520947-0d0a9180-a8dc-11eb-8df1-5bc73f70d079.png)

**Comment by tomasnorre** [comment]
Oh. Mine is at least not cropped, but just resizing my bar.
