### ISSUE TITLE
Can't copy links using right click from Mattermost client on Ubuntu

### ISSUE THREAD

**Issue by alexdor** [mattermost/desktop#348]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Can't copy links using right click option on Ubuntu Gnome 16.04

#### Steps to reproduce

1. Move your cursor to a link
2. Right click it
3. Select copy
4. Try pasting the link to a browser's url bar

- Operating System: Ubuntu Gnome 16.04
- Mattermost Desktop App version 1.3.0
- Mattermost Server version 3.4.0

**Comment by jasonblais** [comment]
Thanks @alexdor for the report,

Mattermost Desktop App v3.4.1 should resolve this issue for the Linux client. Can you try downloading the [latest version?](https://about.mattermost.com/download)

There is a further fix scheduled for the next Windows desktop app release where copying a link address and pasting it inside the app will work properly (fixed by https://github.com/mattermost/desktop/pull/306)

**Comment by alexdor** [comment]
It's fixed indeed :)
