### ISSUE TITLE
Switching to the app should always focus the message text box

### ISSUE THREAD

**Issue by fibbs** [mattermost/desktop#355]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

The text box on the bottom of the app's main window doesn't reliably get focussed when the app is brought to the foreground, in order to start typing without the need to focus the text box manually. This is very bad for the user experience.
#### Steps to reproduce

Tested on macOS Sierra, latest Mattermost Desktop App 3.4.1 on a Mattermost Server Version 3.4.0.
1. mark some text within received messages and observe the cursor disappears from the text box
2. hit cmd-tab to switch to any other application on your desktop
3. send yourself a message through mattermost (from another computer or mobile device)
4. click on the desktop notification to bring mattermost desktop app to the front
5. observe the cursor doesn't activate in the text box

This behavior only applies if the app doesn't have to switch the channel, meaning that the channel within which the message has been received recently was already open in mattermost desktop app.
#### Expected behavior

Message box should be focussed (show the blinking cursor) every time the app is brought to the foreground (switched to it).
#### Observed behavior

The message box doesn't receive focus when the app is brought to the top, and the last action before putting the app to the background was a click within the message stream that made the focus go away from the text box.

**Comment by jasonblais** [comment]
@fibbs Thanks for the feedback!

As a regular Mattermost desktop app user, I share a similar sentiment. It would be nice if the app auto-focused on the message box when brought back to the foreground.

However, I think there are a few corner cases to consider where the focus shouldn't be set to the message box:

 1. an open modal like Account Settings 
 2. any page that doesn't have center channel (e.g. full-page screens, backstage, System Console)
 3. focus already set to right hand sidebar input box or search box

Moreover, if right hand sidebar contains a comment thread AND right hand sidebar is expanded, focus should probably be set to the right hand sidebar instead of the center channel, complicating the situation a little.

--

Mattermost has an [open Help Wanted issue on the server side](https://github.com/mattermost/platform/issues/4142) where if a user types, the focus should always be set to the center channel text input box (apart from the scenarios given above).

Wondering if that would be a proper fix for this issue?

**Comment by yuya-oc** [comment]
Just for reference: #155

**Comment by jasonblais** [comment]
Closing the issue here, since it's not specific to the desktop app.

If you'd like see focus set automatically to the input box on typing, consider upvoting the [existing feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/13248267-auto-focus-cursor-to-input-box-on-typing-or-window) or participate in the discussion of the [GitHub Help Wanted issue](https://github.com/mattermost/platform/issues/4142) on the server side.
