### ISSUE TITLE
Open Links from E-Mails in electron-mattermost

### ISSUE THREAD

**Issue by leipert** [mattermost/desktop#42]
Is there any way to this or how we could hack it?

**Comment by yuya-oc** [comment]
No. OS will open a http(s) link with your default web browser.

Possibly following steps can realize that, but implementation will be complex.

1. Register electron-mattermost as default web browser for http(s).
2. The app check whether the link is mattermost url.
3. If it's mattermost, open it in correct tab.
4. If not, open it in your web browser. Unfortunately, you have to specify web browser manually because the default browser is electron-mattermost in step 1.

Besides, all http(s) link will be opened via electron-mattermost everytime.

**Comment by leipert** [comment]
@yuya-oc If we could support a custom protocol `mattermost:`, we could simply rewrite the protocol in the email templates...

**Comment by yuya-oc** [comment]
Yes, however it forces users to use electron-mattermost or other native clients. So the template should show two links, `http(s)` and mattermost`. How do you think about this?

btw, its there any way to change email template in mattermost?

**Comment by leipert** [comment]
I do not know exactly. I will open an issue at mattermost. Maybe mattermost could make this a user setting...

**Comment by jasl8r** [comment]
How about supporting a url scheme and just using something like this: https://chrome.google.com/webstore/detail/redirector/pajiegeliagebegjdhebejdlknciafen?hl=en-US

**Comment by yuya-oc** [comment]
It's nice. Users have to set regex, but function will be simple.

**Comment by leipert** [comment]
That would be really nice!

**Comment by jasonblais** [comment]
Thanks for the suggestion @leipert! Appreciate your feedback here

We're beginning to move feature requests from GitHub issues to our feature idea forum to keep all feature ideas in one place. Therefore, could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Opened a feature request here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36795994-open-links-from-e-mails-in-electron-mattermost
