### ISSUE TITLE
URL address is shown for internal Mattermost links when hovering with mouse.

### ISSUE THREAD

**Issue by hamishgraham** [mattermost/desktop#427]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
URL address is shown for internal Mattermost links when hovering with mouse.

**Steps to reproduce**

Using macOS 10.12.1 and Desktop Mattermost 3.5.0.

If I hover over any of the channels, flag icon etc then the URL is shown at the bottom of the window. This appears to be a new behaviour in v3.5.0. These "internal" Mattermost URLs were not shown previously. I can understand showing the URL for external URLs for posted content but it's irritating and IMHO unnecessary to show the URL for internal Mattermost links.

**Comment by jasonblais** [comment]
@yuya-oc is this controlled by the Mattermost server, or are there optimizations we can do on our end?

The behaviour currently matches between the web app and the desktop app.

**Comment by yuya-oc** [comment]
The hovering URL is controlled by our side. Currently the app doesn't check a URL, so it's merely appears even if it's internal address.

**Comment by jasonblais** [comment]
Ah okay -- it would make sense then not to show the URL for internal links by default.

Most of them aren't very useful, e.g. 
![image](https://cloud.githubusercontent.com/assets/13119842/22518388/6aa1b584-e87a-11e6-9e81-2fd4d25ad06b.png)

Would it just ignore links that match the server URL?

**Comment by yuya-oc** [comment]
Now what tha app can know is URL string only, so the only way is pattern matching.

For embedded link, I'm not sure whether there is a way to know the link is embedded or not for now.

**Comment by jasonblais** [comment]
Ah, I see. I don't know if we'd want that, since people can use embedded links and it's helpful to see the URL before clicking it.

@hamishgraham how much are the channel URLs bothering you?

For internal links that are shown when hovering over buttons like flags and channel names (see below) are handled on the server side. It might make sense to remove those, what do you think?

![image](https://cloud.githubusercontent.com/assets/13119842/22581735/3f79061e-e9b0-11e6-9eb2-101e3822c6a8.png)

**Comment by hamishgraham** [comment]
I'd get used to it sure but I'm currently using v3.4.1 because of this but I'm sure I'll upgrade at some point. It just seems like unnecessary behaviour given that it's meant to be closer to a native app rather than a web browser. Apps like Skype or Slack don't show internal links.

**Comment by hamishgraham** [comment]
By embedded links, do you mean ones created with markdown like this: "[somesite](http://google.com/)" ?

Then yes it's definitely useful to see the full URL when hovering over these.

**Comment by jasonblais** [comment]
^yeah, that's correct @hamishgraham. That's actually why this feature was added to v3.5, because people were having trouble knowing what the link is before clicking it.

Also, Slack/Skype apps don't show any URL when you hover over them (whether internal or external), at least on Windows 10.

I'll bring it up in our UX design meeting to consider removing internal links in Mattermost webapp for buttons like flags and recent mentions. That will at least help reduce how often you see the URL for internal links.

![image](https://cloud.githubusercontent.com/assets/13119842/22592680/f1dade8a-e9e8-11e6-821e-d3cc966215c6.png)

**Comment by jasonblais** [comment]
Adding a server side label for now -- we're looking at potentially hiding the URL for internal links, such as when hovering over icons.

This should help mitigate how often you see the URL for internal Mattermost links.

**Comment by jasonblais** [comment]
Hey all,

We have a ticket to make some changes on the server side where internal links will be hidden from the UI: https://mattermost.atlassian.net/browse/PLT-6828

The changes will automatically apply to the desktop app.

The improvement is tentatively scheduled for Mattermost server v4.1, released on August 16th.

**Comment by Scotchester** [comment]
Great news! Thanks!

**Comment by Dominik-Andreas-Geng** [comment]
The ticket PLT-6828 will change link-tags (<a>) to button-tags to hide the url? Ok, this is one solution. Another solution: Hide the browser native URL-Display (bottom) and implement a custom Display for URLs etc. For example a popups / popovers like https://semantic-ui.com/modules/popup.html by hovering over a link. Or implement a url protection. When a user clicked on a link, a popup-window (html) is shown with complete url and a forward button. 
Or enable a OS native quickinfo tooltip when hovering the link. 

The browser native url-display on the bottom of the page is really annoying. e.g. its overlapping the "User is typing..." info. etc.

**Comment by jasonblais** [comment]
@Dominik-Andreas-Geng Thanks for the suggestions! Sorry for the late reply,

I'd be curious to hear what advantages your solutions have over changing link-tags to button-tags?

**Comment by Dominik-Andreas-Geng** [comment]
@jasonblais Thanks for the reply. Hmm, advantages ... This wasn't my intention. Just listed a few alternative solutions. At the moment, I cannot guess what disadvantages buttons have. Ok, you should adjust some properties in CSS to remove unwanted behaviours like outline, etc. I think my solutions may looks prettier.  And are independent from browser URL view.
Perhaps we can add a placeholder line at the bottom for the URL view of the browser. (25px height)
To prevent overlapping some text like "User is typing ..." when hovering a link.
But anyway... I just wanted to throw some ideas into this thread. 😄

**Comment by jasonblais** [comment]
Thanks @Dominik-Andreas-Geng! Have forwarded this to our developer who was going to work on this ticket. Appreciate the input! :D

**Comment by asaadmahmood** [comment]
Hey @Dominik-Andreas-Geng, just so I understand, how are popovers, or tooltips going to aid here?
We just want to hide the url bar itself, like we don't see it adding a lot of value, so are you suggesting that we show the url in tooltips etc?

**Comment by Dominik-Andreas-Geng** [comment]
Hi @asaadmahmood, no please not! 😄 Hide the URL bar in any case! Especially for internal links. 
No, I wanted to say: Disable the native url bar of the browser completely and add a own custom url viewer (like a popover or whatever) for links posted by users. 
Why? It just fixed the issue of internal links in any case and looks prettier as the native url bar for user posted liks. Also it adds possibilities like Link-Preview for the feature. Because it's fully HTML. 

This is just an idea I thought about. 
For my understanding, the reason for this ticket is to hide ONLY internal links and not the links posted by users. Of course, the browser (chromium) does not show the targets (links) of buttons. So you can use this for a "quick" implementation. My intention only was to show some other solutions. Regardless from the button-solution. This solution (buttons) is also a great solution for me. 
But I think, It looks more prettier in mattermost-style (html).

Again: Please do not misunderstand my suggestion. I want exactly the same aim as of this ticket.
Remove the display of internal links. But perhaps display the user posted links in a fancy way.

**Comment by asaadmahmood** [comment]
Sure, sounds cool. Thanks for the suggestion :).

**Comment by yuya-oc** [comment]
@jasonblais Recently I have noticed though, by comparing address part of server URL and link URL, we might be able to hide the bar when they are in the same server.

**Comment by jasonblais** [comment]
@yuya-oc Would this be true for user-specified links as well (such as permalinks or Markdown formatted links in the form `[some text](link containing server URL)`

**Comment by yuya-oc** [comment]
@jasonblais Yes. In the idea, the bar doesn't appear when a contained URL is an internal link. (Currently app can know only "URL")

**Comment by jasonblais** [comment]
That makes sense. It might not be desired though, as people might want to know the destination of an embedded link before clicking it.

Once https://github.com/mattermost/mattermost-webapp/pull/53 is merged, it should hide the URL for any links that weren't supplied by the user. I think that might be sufficient for the app too.
