### ISSUE TITLE
Add localization support via Mattermost Translation Server

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#475]
Add localization support via [Mattermost Translation Server](translate.mattermost.com).

The [new mobile apps](https://github.com/mattermost/mattermost-mobile/tree/master/assets/base/i18n) have localization support (although it'll only be in English/Spanish for the beta launch).

We should explore options to support localization of the desktop app, which would consist of all app-specific strings like the menu bar, Settings page, etc.

Best way is to work with Elias from Mattermost team and get it hooked up to the [Translation Server](translate.mattermost.com) that already has a vibrant localization community.

**Comment by LAfricain** [comment]
I can help, if needed for french translation.

**Comment by jasonblais** [comment]
That would be great @LAfricain! 

We have existing translations for the webapp and mobile hosted here, if you're interested helping: https://translate.mattermost.com/projects/mattermost/

The desktop app translations will most likely be handled there too

**Comment by LAfricain** [comment]
> The desktop app translations will most likely be handled there too
I am especially interested in the desktop version...

**Comment by jasonblais** [comment]
Haha got it :) Will let you know when those are added. Thanks again for offering your help

**Comment by wget** [comment]
Hello there. I'm the guy in charge of the French translation for almost 2 years now, I I have just noticed this. Since the French translation is complete for the server, webapp and mobile apps, I definitely think this is is feature needed. When the webapp is set to french and we need to use the desktop app, this looks as if the product was still a draft and not polished enough.

What do you require to make this happen? Parsing things etc? and playing with the Pootle API? This is not a problem for me if you need work force. cc @enahum 

Link to the discussion on the chat: https://pre-release.mattermost.com/core/pl/m6kuy95sfjfp9jcre3trsj4zxr

**Comment by amyblais** [comment]
Moved this to a Story Jira ticket: https://mattermost.atlassian.net/browse/MM-14058.
