### ISSUE TITLE
Create an install wizard for Windows app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#491]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Create an install wizard for Windows app

This is more standard for Windows native apps. 

Needs design before it's ready for implementation.

**Comment by yuya-oc** [comment]
This is a simple example of NSIS installer by electron-builder. It seems that some images can be specified in [the option](https://github.com/electron-userland/electron-builder/wiki/Options#nsisoptions).

https://www.dropbox.com/s/3bcazjk7tuguipv/mattermost-setup-3.6.0-win.exe?dl=0
(Due to version incompatibility of GCC, I can't build the artifact in CircleCI yet)

This issue might be related to other issues like Windows Store (#492) and auto-updater. So I think we need to take care about installer frameworks.

**Comment by towolf** [comment]
Out Office IT has problems pre-installing the desktop app on Windows, because, as of yet, there is apparently no way to install it for "all users":

> We have problems to create a package for deployment. 
>
> Mattermost Client Installer have no installation switches which allows us to install it for all windows users. That means the installation under SYSTEM Account do not work with our software deployment.

I came here from PR #582 where this comment was made:

https://github.com/mattermost/desktop/pull/582#issuecomment-327527062

> Yeah, it means "us". We can choose one of them:
>
> - Per user (under AppData) (current)
> - Per machine (under C:\Program Files)
> - Choose one of them in install wizard
> Whichever we choose one of them, we can add the option to select install location by adding install wizard.
> 
> This should be discussed at #491, but I wanted to tell a little here.

**Comment by amyblais** [comment]
Closing via https://mattermost.atlassian.net/browse/MM-14085
