### ISSUE TITLE
Why does this app make a call to api.segment.io ?

### ISSUE THREAD

**Issue by fmp777** [mattermost/desktop#544]
This is new to one of the later versions - suddenly Mattermost desktop is calling api.segment.io - which is typically used for tracking data in 3rd party services.

Why is this client tracking anything?  Feels less secure with this going on.  Please advise.

**Comment by jasonblais** [comment]
Thanks @fmp777 

You can find out more information here: https://docs.mattermost.com/administration/telemetry.html

It is optional and can be turned off on the server if preferred. No personally identifiable information is collected.

**Comment by jasonblais** [comment]
I'll close the issue since it's related to the Mattermost server rather than the desktop app. Feel free to ask further question though.

**Comment by dannycolin89** [comment]
> @jasonblais : It is optional and can be turned off on the server if preferred. No personally identifiable information is collected.

I think that kind of optional option should be set to disabled by default. In other words, it should be an opt-in option instead of an opt-out one.

**Comment by jelmd** [comment]
I think it is a **big security issue** to use a host, which changes every 60 seconds its IPs in an unpredictable manner. So since reports are blocked by our firewall anyway (impossible to find a static stable IP), we are forced to disable telemetry ...

**Comment by boistordu** [comment]
Hi, 
I didn't want to duplicate this issue. 
So I'm going to continue on this one until advised otherwise.
The pi-hole mattermost server is configured to not have telemetry activated. Their team have shown me the screenshot of the box checked to false in the settings.
Still I have plenty of api.segment.io calls on my dns filtering system which is pi-hole or latter nextdns.

Here are the screenshots that  I4ve taken when I had a problem before unblocking your telemetry partners. 
![accept cert2020-04-26 033705](https://user-images.githubusercontent.com/9523075/80307601-58222e00-87ca-11ea-8e5c-e5c9a26049d3.jpg)
![apsegment_blocked_nextdns2020-04-26 033853](https://user-images.githubusercontent.com/9523075/80307602-59535b00-87ca-11ea-8041-e63dae59d651.jpg)
![certificate error2020-04-26 033534](https://user-images.githubusercontent.com/9523075/80307603-59535b00-87ca-11ea-8d26-83e57f9269dc.jpg)
![segment_being_blocked2020-04-26 035628](https://user-images.githubusercontent.com/9523075/80307604-59ebf180-87ca-11ea-83f2-aada8bbd54da.jpg)

**Comment by akomakom** [comment]
@boistordu FYI, I had to reload (View->Reload) my front end app (Linux v4.3.1, in my case) after disabling reporting in the System Console.  Errors went away after that.
