### ISSUE TITLE
On Windows, Desktop notification duration settings in Control Panel not honoured since v3.7.1

### ISSUE THREAD

**Issue by lip-d** [mattermost/desktop#601]
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
On Windows, Desktop notification duration settings in Control Panel not honoured since version 3.7.1.

**Steps to reproduce**
On Windows:
1. [Control Panel] -> [Ease of Access] -> [Make it easier to focus on tasks] -> [Adjust time limits and flashing visuals]
2. Change the duration to 30 sec for instance. (Any duration greater than 5 sec)
3. Receive a message on Mattermost desktop app (specifically version 3.7.1)

- Operating System
  Windows 7
- Mattermost Desktop App version
  3.7.1. 
- Mattermost Server version
  4.2.0 or any version.

**Expected behavior**
  Desktop notification balloon stays open for more than 5 sec.

**Observed behavior**
  Desktop notification balloon stays open only for 5 sec regardless of the Control Panel settings.

**Possible fixes**
  I am not sure but I assume that this issue is related to the upgrade from 3.7.0 to 3.7.1.
  (Maybe related to Electron upgrade to 1.6.10)  
  I've looked into the source code but failed to find the right place to fix.
  I have disability and 5 sec is too short for me to click on the balloon.  It would be amazing if this issue can be solved. 
  Thanks for all your effort to make this app amazing. 
  Best.

**Comment by yuya-oc** [comment]
I haven't known the setting, thanks!

Since v3.7.1, we changed notifications from system tray balloon to Electron's one in order to solve #67.

Notification is implemented at [brightray](https://github.com/electron/electron/tree/master/brightray/browser/win). I feel [here](https://github.com/electron/electron/blob/v1.8.0/brightray/browser/win/win32_desktop_notifications/toast.cc#L643-L645) is the place to set its duration. And the duration seems to be stored as `HKEY_CURRENT_USER¥Control Panel¥Accessibility¥MessageDuration` in registry. So we might be able to reflect it by creating a PR against to Electron.

**Comment by yuya-oc** [comment]
Added the PR. https://github.com/electron/electron/pull/10517

**Comment by amyblais** [comment]
I tested this and I didn't see this issue (desktop notification balloon stays open for more than 5 sec).

**Comment by lindy65** [comment]
I also tested this (Win10) and it's working as expected for me.

**Comment by lip-d** [comment]
ok on Win10, and not ok on Win7.
- Mattermost desktop app 4.0.0

**Comment by yuya-oc** [comment]
Closed by #711
