### ISSUE TITLE
Multiple *.tmp.ico files accumulating in \AppData\Local\Temp\

### ISSUE THREAD

**Issue by torcso** [mattermost/desktop#621]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

In Desktop version 3.7.1, each time you load the Mattermost program, 3 tmp.ico files are created in the temp directory.

**Expected behavior**

These files should be created once and referenced back to unless they no longer exist.
**Observed behavior**

**Possible fixes**

**Comment by yuya-oc** [comment]
As far as reading Electron source code, it read .ico files from `.asar` archive by generating temporary .ico files. 
https://github.com/electron/electron/blob/v1.8.1/atom/common/api/atom_api_native_image.cc#L168-L184

And I think it seems difficult to remove them because `base::win::ScopedHICON` can't know whether the .ico file is temporary and not referenced. electron/electron#10796

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14136

**Comment by amyblais** [comment]
Closing as the Jira ticket is closed - please re-open if the issue persists on the latest desktop app version v4.4.0,
