### ISSUE TITLE
Mac: Closing the app then reopening no longer shows the app in the menu bar or tab switcher

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#629]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mac: Closing the app then reopening no longer shows the app in the menu bar or tab switcher

**Steps to reproduce**

MacOS; Mattermost server v4.2; Mattermost Desktop App v3.7.1

1. open MM MacOS desktop client
2. cmd+w or click red close button to close the app (but not quit it)
3. check that it does not exist in menu bar OR tab switcher
4. open MM again

**Expected behavior**
Mattermost client appears in the menu bar and the tab switcher

**Observed behavior**

Mattermost client doesn't appear in the menu bar and the tab switcher

----

@yuya-oc We should also check if it's expected that the app appears in the menu bar and tab switcher on step 3 of the repro steps.

**Comment by yuya-oc** [comment]
Not reproduced for me on macOS 10.12.6. The app is kept in `Cmd+Tab` switcher and the menu bar icon exists even when the window is closed (internally, it's hidden instead of closed). Of course, the option should be enabled to show the menu bar icon.

I feel the reporter accidentally used `Cmd+Q` instead. Would you confirm again?

**Comment by MusikPolice** [comment]
Agreed, I can't reproduce this. As @yuya-oc noted, `Cmd+Q` would cause this behaviour, but that's expected.

**Comment by jasonblais** [comment]
The reporter mentioned they used `CMD+W` instead. Is there any additional info I can ask? I can also link you to the report if easier, it was brought up on pre-release.

**Comment by jasonblais** [comment]
^@yuya-oc here's the report. It's a private channel, but you should have access to it https://pre-release.mattermost.com/core/pl/3duiozg6obnkif4yfctjszye9w

**Comment by yuya-oc** [comment]
To make sure, we need to know macOS version and whether the reporter actually uses the latest app.

Perhaps the reporter uses v3.5.0 or earlier. It has an option to hide Dock icon when the window is closed. In that case, the app doesn't exist in the switcher because the icon is not on Dock. If the reporter called the Dock as "menu bar", this assuming would be correct.

**Comment by jasonblais** [comment]
Thanks! Have asked. I thought they mentioned they were using the latest app version but realized they didn't.

**Comment by jasonblais** [comment]
@yuya-oc You're correct, they were on v3.5. Resolved by upgrading to v3.7.1

Closing
