### ISSUE TITLE
Roadmap for v4.1 and v4.2

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#658]
This is a ticket to discuss key items we should consider for the v4.1 and v4.2 releases. 

We are aiming to get back to a regular, bi-monthly release cycle. Given v4.0 is scheduled for mid-December, this means
 - v4.1 is scheduled for mid-February
 - v4.2 is scheduled for mid-April

We already have milestones for [v4.1](https://github.com/mattermost/desktop/milestone/9) and [v4.2](https://github.com/mattermost/desktop/milestone/10), but they're a bit ambitious for the shorter release cycles.

Community is welcome to suggest key features they'd like to see in the coming releases, and we'll take those suggestions into consideration.

@yuya-oc any key items you feel would be important for v4.1 and v4.2? I'll share my thoughts as well based on customer requests.

**Comment by yuya-oc** [comment]
Just for now

### v4.1
It has impact for working time rather than important feature though;
- #457: It might require large rewriting of React components.
- #520: Still we couldn't find what's the root cause. Possibly we might need to move from `webview` to `BrowserView` like Slack, but I'm not sure whether it solves the problem. And it would require significant changes in our code structure.

Others are miscellaneous, so it would be good if they are prioritized. Possibly #399 or #475 look important.

### v4.2
- #608: It looks significantly important. Especially when the app is started by auto-start and it's minimized.
- #539 #566: They would require Mac CI to build macOS app due to native addon. As far as I know, CI services which support macOS are few (CircleCI is supporting, but it's paid plan).

**Comment by jasonblais** [comment]
Thanks! I agree on each. A few others based on customer requests:

#### v4.1
 - https://github.com/mattermost/desktop/issues/657: Will need some design work first
 - https://github.com/mattermost/desktop/issues/632: Bug
 - https://github.com/mattermost/desktop/issues/652: Bug
 - https://github.com/mattermost/desktop/pull/588
 - https://github.com/mattermost/desktop/issues/623: To remove confusion about "teams" in the desktop app
 - https://github.com/mattermost/desktop/issues/583: Bug
 - https://github.com/mattermost/desktop/issues/559: Bug
 - https://github.com/mattermost/desktop/issues/535
 - https://github.com/mattermost/desktop/issues/480

#### v4.2
 - https://github.com/mattermost/desktop/issues/622: This will need some design considerations
 - https://github.com/mattermost/desktop/issues/538
 - https://github.com/mattermost/desktop/issues/617

**Comment by jasonblais** [comment]
I'm wondering how much would be appropriate to include in a two-month release cycle? I don't want to overload you.

We might get Jonathan's help in the coming months as well, working on one desktop app ticket per week, once the build automation and code-signing is finished.

**Comment by jasonblais** [comment]
@yuya-oc I'm wondering how much would be appropriate to include in a two-month release cycle? Maybe an estimate of how many tickets is reasonable to assign to a milestone, given potentially large tickets such as #457 and #520 (e.g. 5 tickets? 8, 10?). I don't want to overload you.

I've also asked our head of product if we can get Jonathan to help full-time on the desktop app in January or February, for one month. I'm thinking he could help with smaller tickets, bugs and community questions, so you can focus on the larger tickets in early 2018.

Let me know what you think,

**Comment by jasonblais** [comment]
Let's try and use the newly-created priority labels from @amyblais. Closing this issue.
