### ISSUE TITLE
Not able to login GitLab Mattermost in Firefox 45.0.2

### ISSUE THREAD

**Issue by mmanoharan83** [mattermost/desktop#663]
```
I'm using CentOS 6.5 with maximux supported firefox version of 45. (Further update not supported by OS)
From this version, not able to get login GUI.
```

`If this issue is not solved, mattermost will be un usable in particular version of firefox.`

**Comment by mmanoharan83** [comment]
Related Issue: https://github.com/mattermost/desktop/issues/662

**Comment by jasonblais** [comment]
Thanks @mmanoharan83 - have you tried Mattermost on Firefox version 45? What errors do you get?

**Comment by mmanoharan83** [comment]
![mattermost-error-in-firefox](https://user-images.githubusercontent.com/17979939/33183734-0dc59034-d09f-11e7-9785-c5830f0e285f.jpeg)

**Comment by jasonblais** [comment]
Thanks @mmanoharan83 for your report,  

Because this seems to be more a troubleshooting discussion server-side that affects a web browser than a product defect on the desktop app, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? There are more forum visitors including Mattermost staff, which means a potentially faster response.

Also, please link back to your new post from this issue?

**Comment by mmanoharan83** [comment]
thanks for your information

**Comment by jasonblais** [comment]
Thanks @mmanoharan83, I'll close this issue and we can continue discussion in the forums
