### ISSUE TITLE
Windows 7: Clicking on notification should open the message

### ISSUE THREAD

**Issue by i23098** [mattermost/desktop#67]
Clicking on notification message, should open the application window in the clicked message. At the moment it just opens/focus on the application, but on whatever channel/direct message it was open before.

**Comment by yuya-oc** [comment]
Please write about your environment. ([CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md))

Then, does this latest build solve the problem?
https://circleci.com/gh/yuya-oc/electron-mattermost/192#artifacts

**Comment by i23098** [comment]
I'm on Windows 7, 64 bits, using electron-mattermost-v1.0.7-win64.

Using the suggested build, same thing happens, clicking on the notification just switch focus to electron-mattermost app, without changing the conversation to the clicked one.

**Comment by yuya-oc** [comment]
It's correct behavior since v0.x. On Windows 7 and 8, Notification API is not supported by [Electron](http://electron.atom.io/docs/v0.36.8/tutorial/desktop-environment-integration/#notifications-windows-linux-os-x
) (to be exact, Windows 8 can support it, but setup will be a little complex).

On Windows 7 and 8, [Tray](http://electron.atom.io/docs/v0.36.8/api/tray/#traydisplayballoonoptions-windows) API is used to show balloon and working at `src/main.js`, it's separated from browser window. So it's hard to implement `Notification.onclick` event.

**Comment by seriema** [comment]
@lunawesley9 did you mean [this comment](https://github.com/electron/electron/issues/262#issuecomment-210208791)? It uses [electron-notification-shim](https://github.com/seriema/electron-notification-shim). I created it with [our HipChat Electron wrapper](https://github.com/kvasir/HipsterChat) in mind.

We had started wrapping it all into a [electron-notifier](https://github.com/kvasir/electron-notifier) for when you just want to add notification toasters for Electron platforms that lack it. We never got around to finishing when the Electron issue got closed as we assumed it'd be as easy on the Mac. If there's interest, we could finish it so feel free to add any issues or submit a PR there.

**Comment by jasonblais** [comment]
@yuya-oc FYI, adding "Help Wanted" tag for issues that are open for community contributions, [following the process from platform repo](https://docs.mattermost.com/process/community-guidelines.html#github-help-wanted-issues-in-platform-repository)

**Comment by jasonblais** [comment]
#543 resolves this issue, thanks @yuya-oc!
