### ISSUE TITLE
Make notification customisable

### ISSUE THREAD

**Issue by edpstiffel** [mattermost/desktop#81]
I would like to have the notification customisable as in Slack, where you can choose to let the notification show either the username/channelname and a fragment of the message, or just the username/channelname.

**Comment by Razzeee** [comment]
The problem here is, that currently we're just passing along the notifications that get generated by platform. It wouldn't be wise to cut up the contents and try to rearrange them. 
We would need some kind of feature in the platform to get the individual fields of the notification.

**Comment by jasonblais** [comment]
Thanks @edpstiffel, appreciate your feedback. Given this suggestion would not be desktop-specific, could we have your help:

1. [Contributing this in the Mattermost feature idea forum](http://www.mattermost.org/feature-ideas/) so it can be discussed, upvoted and considered for a ticket [accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

2. Posting a link back from the feature idea forum to this thread?

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Closing this issue for now, as it pertains to the Mattermost server itself, rather than the desktop app specifically.

I still encourage you to [contribute this idea in the Mattermost feature idea forum](http://www.mattermost.org/feature-ideas/) so it can be discussed, upvoted and considered for a ticket [accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html).
