### ISSUE TITLE
Developed in Electron

### ISSUE THREAD

**Issue by ytpillai** [mattermost/desktop#826]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Everything
- Mattermost Desktop App version:  all 
- Mattermost Server version: all 

**Steps to reproduce**
Download app

**Expected behavior**
Not be Electron

**Observed behavior**
Is Electron

**Possible fixes**
Demolition of project and redevelopment

**Comment by ArchangeGabriel** [comment]
What’s your point? Electron is the _de facto_ standard for embedding web apps into desktop ones. Unless you are providing the resources (in money or developer time) to develop a better alternative that would be a native app, nothing is likely going to happen.

**Comment by ytpillai** [comment]
Ok, so I'll be honest. I was being immature here because  I wanted to see issues reach 69. But I did have a serious question/suggestion, think I forgot to put it up, would you guys be down to try out QT?  I'd be interested in helping.

**Comment by yuya-oc** [comment]
I didn’t try Qt. Right now, I took a look Qt documentation. Possibly Qt WebEngine might be usable for us.
https://doc.qt.io/archives/qt-5.10/qtwebengine-index.html

Honestly developing with JavaScript is not so important for me. When I had started this project, of course I could choose full-native. But I thought that I couldn’t follow up frequently-progressed webapp features in my developer time. By using webview, the desktop app can provide appropriate features without taking care of various Mattermost server/webapp versions. And Electron is explicitly using a certain version of Chromium, so that helped us by researching well-known issues when troubleshooting.

**Comment by ytpillai** [comment]
I'm not very experienced in either by any means, and have only tinkered. The reason why I wanted to make the suggestion (ok, I had a bit of fun but being serious now) was because of the resource usage that Electron has. I mean, being honest, who wants a lot of system resources being used by a chat app? Especially one with a website where you can just have a browser tab open somewhere instead of installing XYZ into your system? 

Also, I [http://blog.qt.io/blog/2013/09/12/introducing-the-qt-webengine/](think qt webengine is based on chromium too). You can also have a better compatibility with actually interacting with the OS because, well, C++.

**Comment by yuya-oc** [comment]
Thanks for your kind suggestion. IMHO, or rather I would like to have an app apart from a browser in order to use as a resident app even if it's webapp based. That's the primary reason I wanted the app. And if functionality was less than webapp, eventually anyone wouldn't use the app unless it focuses on simple usecase. Unfortunately I'm not sure how they think about system resource usage of Electron though.

As a practical problem, in the situation we need to support the current desktop app, rewriting everything from zero is unreasonable. Of course you can develop a better alternative.
