### ISSUE TITLE
When Mattermost obtains focus, always start typing in the message textfield when appropriate

### ISSUE THREAD

**Issue by ylluminate** [mattermost/desktop#840]
One problem that I think most of us have experienced is when we click into the Mattermost client expecting to rip out a message on the tip of our fingers... and as we start to type, we find out that the darn input field "Write a message" is not focused!  This can be very frustrating.

It seems that much of the time the Mattermost client get's it right and you can click in the client or cmd-tab and bam, you're in business... but sometimes if you click in the "wrong spot" (and I'm not entirely sure what that is, perhaps quotes or rendered URL previews are a couple) and you can't type.  Instead of you have to click again down into the input field.

Mattermost should handle input field focus better.  Whenever keyboard entry happens and another location is not specifically selected like a search field or some config field, etc. the text input field for writing messages should be automatically focused and ready to go at the stroke of a finger.

**Comment by yuya-oc** [comment]
Hi @ylluminate, thanks for feedback. For reference, would you provide about your environment?

- OS
- Desktop app version
- Mattermost server version

If the problem is also for web browsers, would you make an issue for https://github.com/mattermost/mattermost-server? You would get more detailed feedback.

If you are on macOS app, I think #534 is a similar issue. At that time, we could not control the focus when the window is activated. Now Electron's BrowserWindow has `acceptFirstMouse` option. If you are interested to make a PR, would you try this?

**Comment by yuya-oc** [comment]
> I'm not entirely sure if #534 is related... In this case I can click twice, thrice, or more times and it NEVER get's the text input field focused until I click on that field itself...

Assuming that, it's an issue for the webapp (mattermost-server), not the desktop app. #534 is merely a way to transfer mouse events to webapp on a native window instance, so it's not related.

@jasonblais @esethna I think a new issue should be opened for webapp.

**Comment by ylluminate** [comment]
Thank you @yuya-oc I've created that for us here: https://github.com/mattermost/mattermost-server/issues/9340
