### ISSUE TITLE
Right to left

### ISSUE THREAD

**Issue by Mohammadwh** [mattermost/desktop#857]
hello please update mattermost and add Right to left for persian and arabic

**Comment by yuya-oc** [comment]
Would you describe more in detail? It seems that the UI is not Mattermost.

- What is your problem?
- Does the problem happen also on web browsers? (We need to tell whether the issue is for webapp or desktop)

**Comment by Mohammadwh** [comment]
its example for Right to left
and this problem for all version

**Comment by yuya-oc** [comment]
Well, eventually what should we do? We're not sure what you are seeing because there are no screenshots about Mattermost. And probably I would not be able to understand anything only from screenshots.

- What is your problem? Please describe with screenshots and annotation.
- Does the problem happen also on web browsers such as Chrome? It would be very helpful as a first step in order to investigate the problem.

**Comment by HosseinAgha** [comment]
@yuya-oc The issues section is closed in mattermost-webapp

**Comment by amyblais** [comment]
Closing this via an existing feature request ticket: https://mattermost.uservoice.com/forums/306457-general/suggestions/15008277-implement-automatic-right-to-left-rtl.
