### ISSUE TITLE
option-return doesn't work in Mac desktop app

### ISSUE THREAD

**Issue by DanShockley** [mattermost/desktop#871]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question.
- [x] This doesn't reproduce on web browsers (such as in Chrome). 
- [x] I have read [contributing guidelines]

---

https://mattermost.atlassian.net/browse/MM-14177

**Summary**
While editing a message, the Option-Return keystroke is not supported in the Mac desktop app, although it works properly in the web app. 

**Environment**
- Operating System: macOS 10.12.6 Sierra
- Mattermost Desktop App version: 4.1.2 
- Mattermost Server version: 5.3.1

**Steps to reproduce**

While typing a message, hit Option-Return  (aka Option-Enter) on the keyboard. 

**Expected behavior**

A Carriage Return character should be inserted (as it behaves on the web app and most other apps). 

**Observed behavior**

No character is inserted. Nothing happens at all. 

**Possible fixes**

Workaround: use Shift-Return, which works to insert a return character. Option-Return is the most commonly used way to insert a return character in an interface text edit box when a hit on the Return/Enter key (with no modifier) is being used to trigger transmission of the message.

**Comment by yuya-oc** [comment]
@esethna I think this is a proposal for keystroke on webapp. Would you check this?

**Comment by DanShockley** [comment]
This is not a proposal for a keystroke in the webapp. 
This is a report that a keystroke that already _does_ work in the webapp, and is a fairly standard Mac keystroke, for some reason does _not_ work in the Mac Desktop app.

**Comment by yuya-oc** [comment]
Well, probably I could not notice or understand the behavior on my Mac (Chrome and Safari). Would you tell us any apps I can easily see the behavior? Or would you provide a gif animation to show your expected behavior?

**Comment by DanShockley** [comment]
Ok. In Safari, this issue does NOT happen. The option-return keystroke properly inserts a carriage return. However, I filed this issue in _desktop_, since the Mac _desktop_ app (not Safari!) ignores the option part of option-return. When you do an option-return keystroke in the _desktop_ app, it treats it like a naked Return keypress and transmits your message.

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14177.

**Comment by hunterlester** [comment]
Verified, `option+return` functions within web app in Safari.
However, it does not function within web app in Firefox nor in Google Chrome.

Verified, Slack web app does offer `option+return` function in Firefox and Google Chrome.

So, if we implement this behavior in the desktop application, we'd also have to duplicate the implementation in the web app, so that macOS users would have a consistent experience.

Plus, implementing it in the desktop app, in the webview preload script, wouldn't be a reliable a way to control `textarea` style and would make further maintenance confusing.

Recommending that this behavior is implemented in web app and not desktop.
