### ISSUE TITLE
"Settings" page buttons do not return to main display

### ISSUE THREAD

**Issue by OmanF** [mattermost/desktop#89]
When going to the settings page ("File" -> "Settings"), pressing either the "Save" button or "Cancel" button do not return to the main display. User ***must*** quit the application ***(at the traybar)*** and relaunch it.

**Note**: The *functionality* of the buttons works correctly (AFAIK), meaning "Save" will save changes, and "Cancel" disregard changes. It's a GUI thing.

**Comment by yuya-oc** [comment]
Please tell me about your environment? (see also [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md))

* Application version
* Operating system

**Comment by bakoonin** [comment]
Have the same issue on Windows 7 x64 Enterprise and Window 8.1 Professional. Can't remember if I tried on Windows 10.

My solution was to autoprovision config.json to all users with `hideMenuBar` set to true, and hope people don't create more teams until it is fixed ;)

**Comment by makzr** [comment]
I encounter the same problem. I'm using version 1.1.0 and Windows 10 x64.
The button do save/cancel when you click'em. However they do not "close" the settings screen.
The only way back is CTRL+Q

**Comment by dirvo** [comment]
I also experience the same issue on Windows 8.1 and Mattermost Client 1.1.0. 

The issue seems to only occur if there is a blank in the path where the client is installed. When starting the client from e.g. `C:\Mattermost\Mattermost.exe`, _Cancel_ and _Save_ close the _Settings_ page, but when the path contains a blank (e.g. `C:\Matter Most\Mattermost.exe`) the buttons do not work.

**Comment by yuya-oc** [comment]
Reproduced. Thanks.
