### ISSUE TITLE
Publish releases to GitHub release artifacts

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/desktop#891]
Would be good if release artifacts could be published to https://github.com/mattermost/desktop/releases. Companies using Mattermost have strict download rules and many can mirror GitHub releases more easily than https://releases.mattermost.com.

**Comment by wget** [comment]
I don't understand. Artefacts are already published on that page. If of course by artefact you meant sources and compiled binaries/installers.

**Comment by bbodenmiller** [comment]
I'm taking exe's, etc. Right now that page only links to artifacts on https://releases.mattermost.com/ rather than hosts them under assets on https://github.com/mattermost/desktop/releases. For example see how https://github.com/git-for-windows/git/releases does it.

**Comment by wget** [comment]
@bbodenmiller Ok understood. I'm aware of the issue and since the msi installers will be released very soon, my intentions are to redo the CI configuration: migrate from circleci to travisci and appveyor.
I'm just being blocked because of right restriction on the repo. This will be fixed very soon as I plan to have a call with the CTO next week to fix this :)

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14180.

**Comment by Willyfrog** [comment]
@amyblais since I'm already working on automating the whole release process, i'll do this as well.

**Comment by Willyfrog** [comment]
should be fixed on https://github.com/mattermost/desktop/pull/1063
